inherit_from: ./configs/Dynamic/DyCheck/dycheck.yaml
scene: mochi-high-five

data:
  input_folder: ROOT_FOLDER_PLACEHOLDER/mochi-high-five
cam:  #intrinsic is different per scene in DyCheck
  H: 960 
  W: 720 
  fx: 741.125543
  fy: 741.125543
  cx: 360.000000
  cy: 480.000000
