inherit_from: ./configs/Dynamic/DyCheck/dycheck.yaml
scene: paper-windmill

data:
  input_folder: ROOT_FOLDER_PLACEHOLDER/paper-windmill
cam:  #intrinsic is different per scene in DyCheck
  H: 960 
  W: 720 
  fx: 710.408897
  fy: 710.408897
  cx: 360.000000
  cy: 480.000000
