inherit_from: ./configs/Dynamic/Bonn/bonn_dynamic.yaml
scene: bonn_balloon

data:
  input_folder: ROOT_FOLDER_PLACEHOLDER/rgbd_bonn_balloon

tracking:
  buffer: 150        # 原来350，减少关键帧缓存
  frontend:
    window: 15       # 原来25，减少局部BA窗口
    max_factors: 50  # 原来75，减少最大边数inherit_from: ./configs/Dynamic/Bonn/bonn_dynamic.yaml
scene: bonn_balloon